name: slack-alert-action
description: "Action to send slack payload to public-sdk-events channel"

inputs:
  heading_text:
    required: true
    description: "Heading of the slack payload"
  alert_type:
    required: true
    description: "type of the slack alert"
  job_status:
    required: true
    description: "status of the job"
  XERO_SLACK_WEBHOOK_URL:
    required: true
    description: "webhook url for channel - public-sdk-events"
  job_url:
    required: true
    description: "job run id link"
  button_type:
    required: true
    description: "color for the check logs button"
  package_version:
    required: true
    description: "released package version"
  repo_link:
    required: true
    description: "link of the repo"


runs:
  using: "composite"

  steps:

      - name: Send slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        env:
          SLACK_WEBHOOK_URL: ${{inputs.XERO_SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
         payload: |
          {
            "blocks": [
              {
                "type": "rich_text",
                "elements": [
                  {
                    "type": "rich_text_section",
                    "elements": [
                      {
                        "type": "text",
                        "text": "${{inputs.heading_text}} ",
                        "style": {
                          "bold": true
                        }
                      },
                      {
                        "type": "emoji",
                        "name": "${{inputs.alert_type}}"
                      }
                    ]
                  }
                ]
              },
              {
                "type": "divider"
              },
             {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* \n ${{inputs.repo_link}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\n ${{inputs.job_status}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Package Version:*\n ${{inputs.package_version}}"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Check the logs",
                      "emoji": true
                  },
                    "style": "${{inputs.button_type}}",
                    "url": "${{inputs.job_url}}"
                  }
                ]
              }
            ]
          }
