name: Node Build, Lint and Test

on:
    push:

jobs:
    build-test-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout xero-node repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/xero-node
                path: xero-node

            - name: Set up Node environment
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: '**/package-lock.json'

            - name: Install dependencies
              run: npm ci
              working-directory: xero-node

            - name: Check for vulnerabilities
              run: npm audit || true
              working-directory: xero-node

            - name: Run Build
              run: npm run build
              working-directory: xero-node

            - name: Run Tests
              run: npm run test
              working-directory: xero-node
