name: Publish
on:
  release:
    types: [published]
  pull_request:
    paths:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout xero-node repo
        uses: actions/checkout@v4
        with:
          repository: XeroAPI/xero-node
          path: xero-node

      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: xero-node

      - name: Run Build
        run: npm run build
        working-directory: xero-node

      - name: Publish to npm
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        working-directory: xero-node

  notify-slack-on-success:
    runs-on: ubuntu-latest
    needs: publish
    if: success()
    steps:
      - name: Send slack notification on success
        run: echo "Slack alert on success"

  notify-slack-on-failure:
    runs-on: ubuntu-latest
    needs: publish
    if: failure()
    steps:
      - name: Send slack notification on failure
        run: echo "Slack alert on failure"
