name: Publish
on:
  release:
    types: [published]
  pull_request:
    paths:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout xero-node repo
        uses: actions/checkout@v4
        with:
          repository: XeroAPI/xero-node
          path: xero-node

      # - name: Set up Node environment
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'
      #     cache-dependency-path: '**/package-lock.json'
      #     registry-url: 'https://registry.npmjs.org'

      # - name: Install dependencies
      #   run: npm ci
      #   working-directory: xero-node

      # - name: Run Build
      #   run: npm run build
      #   working-directory: xero-node

      - name: Publish to npm
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        working-directory: xero-node

  notify-slack-on-success:
    runs-on: ubuntu-latest
    needs: publish
    if: success()
    steps:
      - name: Checkout xero-node repo
        uses: actions/checkout@v4
        with:
          repository: XeroAPI/xero-node
          path: xero-node

      - name: Send slack notification on success
        uses: ./xero-node/.github/actions/notify-slack
        with:
         heading_text: "Publish job has succeeded !"
         alert_type: "good"
         job_status: ${{job.status}}
         XERO_SLACK_WEBHOOK_URL: ${{secrets.XERO_SLACK_WEBHOOK_URL}}
         job_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
         bot_token: ${{secrets.XERO_SLACK_BOT_TOKEN}}
         channel_id: 'C07S29J583U'

  notify-slack-on-failure:
    runs-on: ubuntu-latest
    needs: publish
    if: failure()
    steps:
      - name: Checkout xero-node repo
        uses: actions/checkout@v4
        with:
         repository: XeroAPI/xero-node
         path: xero-node

      - name: Send slack notification on failure
        uses: ./xero-node/.github/actions/notify-slack
        with:
          heading_text: "Publish job has failed !"
          alert_type: "danger"
          job_status: ${{job.status}}
          XERO_SLACK_WEBHOOK_URL: ${{secrets.XERO_SLACK_WEBHOOK_URL}}
          job_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          repository_name: ${{github.repository}}
          bot_token: ${{secrets.SLACK_BOT_TOKEN}}
          channel_id: 'C07S29J583U'
